apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/install.yaml
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/cybozu/argocd
    newTag: 2.2.5.1
  - name: quay.io/cybozu/dex
    newTag: 2.30.2.1
  - name: quay.io/cybozu/redis
    newTag: 6.2.6.1
