apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
  - name: nginx-cm
    namespace: default
    files:
      - files/nginx.conf
